### ISSUE TITLE
Opens new buffer with some random name after running tests

### ISSUE THREAD

**Issue by AmitThakur** [chazmcgarvey/vimcoder#22]
I'm using Vim (gvim) v7.4.1689. with `gvim` as vim command in the plugin configuration.

Whenever I execute `:make run` or `:make test` it runs all the test cases fine and creates a new buffer with the some name like `ok 1 - "0`.

![vimcoder_pic1](https://cloud.githubusercontent.com/assets/1652517/24182700/73f38ac8-0ee9-11e7-85cd-42754bb5696e.png)

and when I press enter to get back to my program code buffer, it takes me to the newly created buffer which is blank.

![vimcoder_pic2](https://cloud.githubusercontent.com/assets/1652517/24182701/73f41704-0ee9-11e7-8de6-91e29c571ba1.png)

**Comment by chazmcgarvey** [comment]
The problem is that Vim is interpreting the test program output as if it were compiler output. It does this because it is trying to populate the quickfix list.

To work around this, you could use `:!make run` instead of `:make run` (notice the extra bang in there). This will run make without causing Vim to try to parse its output.

Alternatively, you could fiddle around with your `errorformat` setting and try to get it to ignore lines from the test program. Something like this could work:

    :set errorformat^=%Enot\ ok\ %l\ %m,%-Gok\ %l\ %m,%-G#%m,%-GTAP\ version\ %*\\d,%-G%*\\d..%*\\d,%-Gmake:\ %m,

This just marks lines that start with "not ok" as errors and ignores some other patterns. See `:help errormarker` for more info.

**Comment by AmitThakur** [comment]
The command `:!make run` works nicely. I'll look out for `errorFormat` setting as well.
Thank you!
